language:
 - php

cache:
  apt: true
  directories:
    - ~/.composer/
    - ${TRAVIS_BUILD_DIR}/travis/module-cache

services:
 - mongodb

php:
 - 5.5
 - 5.6
 - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
  - mkdir -p build/logs
  - sudo apt-get install -y libldap2-dev
  - yes | pecl install -f mongo-1.5.0
  - composer install --dev

script:
  - (cd "test" ; ../vendor/bin/phpunit -c phpunit.xml --coverage-clover ../build/logs/clover.xml --stop-on-failure)
  - vendor/bin/phpcs --standard=PSR2 module/ --ignore="*/test/*,autoload_classmap.php,*.js"
  - vendor/bin/phpmd module text "codesize,naming" --exclude "*/test/*,*/autoload_classmap.php,*.js"
