<?php
$this->layout('layout/error-layout')
?>
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="row">
            <div class="col-sm-12">
                <div class="text-center error-box">
                    <h1 class="error-text tada animated">
                        <i class="fa fa-times-circle text-danger error-icon-shadow"></i>
                        Not Authorized
                    </h1>

                    <h2 class="font-xl">
                        <strong>Sorry! No can do!</strong>
                    </h2>

                    <br />

                    <p class="lead semi-bold">
                        <strong>You have tried to access something you don&CloseCurlyQuote;t have access too.</strong>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
