<?php
$this->layout('layout/error-layout')
?>
<style>
.error-text-2 {
    text-align: center;
    font-size: 700%;
    font-weight: bold;
    font-weight: 100;
    color: #333;
    line-height: 1;
    letter-spacing: -.05em;
    background-image: -webkit-linear-gradient(92deg,#333,#ed1c24);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
}
</style>

<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="row">
            <div class="col-sm-12">
                <div class="text-center error-box">
                    <h1 class="error-text-2 bounceInDown animated">
                        Error 404
                    </h1>

                    <h2 class="font-xl">
                        <strong>
                            <i class="fa fa-fw fa-warning fa-lg text-warning"></i>
                            Page <u>Not</u> Found
                        </strong>
                    </h2>
                    <br />
                    <p class="lead">
                        The page you requested could not be found, either contact your webmaster or try again.
                        Use your browsers <b>Back</b> button to navigate to the page you have prevously come from
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
