<?php
$this->layout('layout/error-layout')
?>
<style>
    .error-text-2 {
        text-align: center;
        font-size: 700%;
        font-weight: bold;
        font-weight: 100;
        color: #333;
        line-height: 1;
        letter-spacing: -.05em;
        background-image: -webkit-linear-gradient(92deg,#333,#ed1c24);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
    }
</style>
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="row">
            <div class="col-sm-12">
                <div class="text-center error-box">
                    <h1 class="error-text-2 bounceInDown animated">
                        Sorry! Our bad
                    </h1>
                    <h2 class="font-xl">
                        <strong>
                            <i class="fa fa-fw fa-warning fa-lg text-warning"></i>
                            We got the error as well and will work to fix it
                        </strong>
                    </h2>

                    <h4>If problem continues, please contact support</h4>

                    <div class="row">
                        <div class="col-md-4 col-md-offset-4">
                            <a class="btn btn-primary btn-lg btn-block" role="button" href="<?= $this->url('admin');?>">
                                Back home
                            </a>
                        </div>
                    </div>

                    <div class="text-left">
                        <?php if (isset($this->display_exceptions) && $this->display_exceptions): ?>
                            <hr/>
                            <p><?=$this->translate('For privileged eyes only') ?>:</p>
                            <p><?= get_class($this->exception); ?></p>


                            <?php if(isset($this->exception) && $this->exception instanceof Exception): ?>
                                <dl>
                                    <dt><?= $this->translate('File') ?>:</dt>
                                    <dd>
                                        <pre><?= $this->exception->getFile() ?>:<?= $this->exception->getLine() ?></pre>
                                    </dd>
                                    <dt><?= $this->translate('Message') ?>:</dt>
                                    <dd>
                                        <pre><?= $this->exception->getMessage() ?></pre>
                                    </dd>
                                    <dt><?= $this->translate('Stack trace') ?>:</dt>
                                    <dd>
                                        <pre><?= $this->exception->getTraceAsString() ?></pre>
                                    </dd>
                                </dl>

                                <?php
                                $exception = $this->exception->getPrevious();
                                if ($exception) :
                                ?>
                                    <hr/>
                                    <h2><?= $this->translate('Previous exceptions') ?>:</h2>
                                    <ul class="unstyled">
                                        <?php while($exception) : ?>
                                            <li>
                                                <h3><?= get_class($exception); ?></h3>
                                                <dl>
                                                    <dt><?= $this->translate('File') ?>:</dt>
                                                    <dd>
                                                        <pre><?= $exception->getFile() ?>:<?= $exception->getLine() ?></pre>
                                                    </dd>
                                                    <dt><?= $this->translate('Message') ?>:</dt>
                                                    <dd>
                                                        <pre><?= $exception->getMessage() ?></pre>
                                                    </dd>
                                                    <dt><?= $this->translate('Stack trace') ?>:</dt>
                                                    <dd>
                                                        <pre><?= $exception->getTraceAsString() ?></pre>
                                                    </dd>
                                                </dl>
                                            </li>
                                            <?php
                                            $exception = $exception->getPrevious();
                                        endwhile;
                                        ?>
                                    </ul>
                                <?php endif; ?>
                            <?php endif ?>
                        <?php endif ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
