<!DOCTYPE html>
<html lang="en" id="extr-page">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta charset="utf-8">

    <link rel="icon" type="image/png" href="/img/favicon.ico" />

    <?php $this->headTitle()->setSeparator(' - ')->append('Help Us'); ?>
    <?= $this->headTitle(); ?>
</head>
<body>
    <header id="header">

        <div id="logo-group">
            <div class="navbar-header">
                <a class="navbar-brand" href="#"></a>
            </div>
        </div>

    </header>

    <div id="main" role="main">
        <?= $this->content; ?>
    </div>
</body>
</html>
