<!DOCTYPE html>
<html lang="en" id="extr-page" class="body-sec">
<head profile="http://www.w3.org/2005/10/profile">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta charset="utf-8">

    <link rel="icon" type="image/png" href="/img/favicon.ico" />

    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

    <link href="//fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,300,400,700" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="/css/sando.css" />
    <?php $this->headTitle()->setSeparator(' - ')->append('Sales & Orders'); ?>
    <?= $this->headTitle(); ?>
</head>
<body class="smart-style-2 fixed-navigation fixed-ribbon fixed-header fixed-page-footer" style="background: none !important;">
    <header id="header">
        <div id="logo-group">
            <div class="navbar-header">
                <a class="navbar-brand" href="#"></a>
            </div>
        </div>

        <span id="extr-page-header-space">
            <span class="hidden-mobile">Need Help?</span>
            <a href="http://support.salesandorders.com" target="_blank" class="btn btn-danger">Support</a>
        </span>

    </header>

    <div id="main" role="main" class="main-login">
        <?= $this->content; ?>
    </div>
    <?php
    /** @var \Zend\View\Helper\FlashMessenger $flash */
    $flash = $this->flashMessenger()
        ->setMessageSeparatorString('</p><p>')
        ->setMessageCloseString('</p>"});');
    ?>

    <script src="/js/vendor-ui.js"></script>
    <script src="/js/vendor-angular.js"></script>
    <script src="/ui/vendor-smart.js"></script>

    <script>
        $( document ).ready(function() {
            <?php $flash->setMessageOpenFormat('$.smallBox({
                title: "Error",
                color: "#C46A69",
                timeout: 6000,
                icon : "fa fa-exclamation-triangle",
                content: "<p>');?>
            <?= $flash->render('error', ['#C46A69']); ?>

            <?php $flash->setMessageOpenFormat('$.smallBox({
                title: "Info",
                color: "#3276B1",
                timeout: 6000,
                icon : "fa fa-info-circle",
                content: "<p>');?>
            <?= $flash->render('info', ['#3276B1']); ?>

            <?php $flash->setMessageOpenFormat('$.smallBox({
                title: "Notice",
                color: "#C79121",
                timeout: 6000,
                icon : "fa fa-warning shake animated",
                content: "<p>');?>
            <?= $flash->render('default', ['#C79121']); ?>

            <?php $flash->setMessageOpenFormat('$.smallBox({
                title: "Success",
                color: "#739E73",
                icon : "fa fa-check",
                timeout: 6000,
                content: "<p>');?>
            <?= $flash->render('success', ['#739E73']); ?>
        });
    </script>

    <?= $this->inlineScript(); ?>
    <!-- Elevio -->
    <script>
        var _elev = window._elev || {};(function() {var i,e;i=document.createElement("script"),i.type='text/javascript';i.async=1,i.src="https://static.elev.io/js/v3.js",e=document.getElementsByTagName("script")[0],e.parentNode.insertBefore(i,e);})();
        _elev.account_id = '5500375a7e65c';
    </script>
    <!--  MouseStats:Begin  -->
    <script type="text/javascript">
        var MouseStats_Commands = MouseStats_Commands ? MouseStats_Commands : [];
        (function () {
            if(document.getElementById('MouseStatsTrackingScript') == undefined) {
                var mousestats_script = document.createElement('script');
                mousestats_script.type = 'text/javascript';
                mousestats_script.id = 'MouseStatsTrackingScript';
                mousestats_script.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www2') + '.mousestats.com/js/4/7/4778809032281936450.js?' + Math.floor(new Date().getTime()/600000);
                mousestats_script.async = true;
                (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(mousestats_script);
            } })();
    </script>
    <!--  MouseStats:End  -->
</body>
</html>
